### ISSUE TITLE
"No Home Page found" Title

### ISSUE THREAD

**Issue by qpty** [gerardnico/dokuwiki-plugin-minimap#1]
When enabling the plugin and creating a page within a namespace (I.E wiki:test) and using the default  insertion of a minimap "<minimap suppress="">" - the menu displayed lists the pages within the current namespace but doesn't display the namespace title in the header cell.  Instead the text "No Home Page found" is displayed then the number of pages.

Attached is a screenshot demonstrating this (the screenshot shows the Bootstrap3 template installed, however the issue still exists with this uninstalled).
![image](https://cloud.githubusercontent.com/assets/11939614/11631014/005b0e92-9cf8-11e5-9996-a5ff89af1e3f.png)

**Comment by gerardnico** [comment]
A home page is a page named:
-  normally 'start'. See the [startpage configuration](https://www.dokuwiki.org/config:startpage)
- of the name of your namespace

For instance, with your page wiki:test, a home page would be:
- wiki:start
- or wiki:wiki 

There was also an error on the finding of an home page that I have already corrected with this commit:
https://github.com/gerardnico/dokuwiki-plugin-minimap/commit/392eeb57c8ecfc447ae74d68e371b46f45663819 Which version do you have ?

**Comment by pozdeiev** [comment]
Do I understand right: I have to create page "start" for every namespace? But it doesn't help me, error still presents with the same number of pages.
Plugin was installed today by Extension Manager.

**Comment by pozdeiev** [comment]
Just installed from github - same issue.

**Comment by gerardnico** [comment]
You may encounter a cache problem.

Two things:
- Update the plugin one more time. I have suppressed all cache mechanism.
- In your sidebar, add the following `~~NOCACHE~~`. See [How can I have an automatic navigation in my sidebar?](https://www.dokuwiki.org/faq:sidebar#how_can_i_have_an_automatic_navigation_in_my_sidebar) 

If you still encounter the problem when previewing/editing your sidebar page, please gives me an test URL.

Cheers
Nico

**Comment by vaniwiki** [comment]
Hi Gerard, I am using your theme, somewhat changed, on my website residing at prabhupada.io (spiritual topics). I just installed the minimap, and it is great! I just have one small itch with it, and that relates to showing No Home Page Found. You see, there's a third way to make a start page.

The start page for "wiki" would simply be named `wiki.txt`, not in itself, but its parent namespace, alongside its folder. The url naming convention makes this a desirable option for me, and a better fit with browsing my hierarchical layers (browsing start pages but viewing parent namespace).

With a tiny uncomment in the DokuWiki codebase I have no issues with priority of these pages (DokuWiki still thinks you want to make a `start.txt` for a new namespace, although of my thousands of namespaces, I only have one `start.txt`, in root, where one actually starts.)

My actual question is if this could be looked into, if these is an easy way that DokuWiki lets you choose this start page as an option also, ie. easy to implement. Thanking you in advance for any clarification on this matter. :)

**Comment by gerardnico** [comment]
@ahaituki 

If I understand it well, your wiki structure is:
- wiki/...
- wiki.txt
which means that you have a page in the parent with the same name than the namespace.

You need to put the wiki.txt file in the wiki directory. It does not change much. The URL naming convention should not suffer from that.

I don't understand why it's not a good case for you.

That's not an easy fix and I have other priorities.
The code is here if you want to have a look
https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/syntax/minisyntax.php#L318

**Comment by vaniwiki** [comment]
Yes, that structure is correct. If I could use rewrite rules to eliminate the actual `:start` part of the url, then it wouldn't make a difference and I could get onboard with the whole start-page thing. Otherwise, being forced to use "namespace:start" or "namespace:namespace" as the start page for, well... "namespace", when "namespace" could just be its own start page... Wait, isn't it this: https://github.com/gerardnico/dokuwiki-plugin-minimap/blob/master/syntax/minisyntax.php#L331
